application:
  name: gitlab
  namespace: gitlab
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/gitlab.git
  # renovate: datasource=gitlab-tags depName=big-bang/product/packages/gitlab registryUrl=https://repo1.dso.mil
  tag: 6.11.3-bb.0
  values: |
    ###ZARF_VAR_GITLAB_VALUES###
