# hostname is deprecated and replaced with domain. But if hostname exists then use it.
hostname: bigbang.dev
domain: bigbang.dev

# Define variables to help with conditionals later

openshift: false

istio:
  enabled: true
  injection: enabled
  gitlab:
    gateways:
    - istio-system/tenant
  registry:
    gateways:
    - istio-system/tenant

monitoring:
  enabled: true

networkPolicies:
  enabled: true
  ingressLabels:
    app: tenant-ingressgateway
    istio: null
  controlPlaneCidr: 0.0.0.0/0
redis:
  metrics:
    serviceMonitor:
      enabled: true
      namespace: gitlab
  master:
    podAnnotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
  slave:
    podAnnotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
postgresql:
  master:
    podAnnotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
  slave:
    podAnnotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
registry:
  annotations:
  # renovate this
    bigbang.dev/istioVersion: 1.17.2
  metrics:
    serviceMonitor:
      endpointConfig:
        scheme: https
        tlsConfig:
          caFile: /etc/prom-certs/root-cert.pem
          certFile: /etc/prom-certs/cert-chain.pem
          keyFile: /etc/prom-certs/key.pem
          insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate

gitlab:
  toolbox:
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
  gitlab-exporter:
    enabled: true
    metrics:
      annotations:
      # renovate this
        bigbang.dev/istioVersion: 1.17.2
      serviceMonitor:
        endpointConfig:
          scheme: https
          tlsConfig:
            caFile: /etc/prom-certs/root-cert.pem
            certFile: /etc/prom-certs/cert-chain.pem
            keyFile: /etc/prom-certs/key.pem
            insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
  webservice:
    metrics:
      serviceMonitor:
        endpointConfig:
          scheme: https
          tlsConfig:
            caFile: /etc/prom-certs/root-cert.pem
            certFile: /etc/prom-certs/cert-chain.pem
            keyFile: /etc/prom-certs/key.pem
            insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
    workhorse:
      metrics:
        serviceMonitor:
          endpointConfig:
            scheme: https
            tlsConfig:
              caFile: /etc/prom-certs/root-cert.pem
              certFile: /etc/prom-certs/cert-chain.pem
              keyFile: /etc/prom-certs/key.pem
              insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
  sidekiq:
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
  migrations:
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
  gitaly:
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
    metrics:
      serviceMonitor:
        endpointConfig:
          scheme: https
          tlsConfig:
            caFile: /etc/prom-certs/root-cert.pem
            certFile: /etc/prom-certs/cert-chain.pem
            keyFile: /etc/prom-certs/key.pem
            insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
  gitlab-shell:
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
    metrics:
      serviceMonitor:
        endpointConfig:
          scheme: https
          tlsConfig:
            caFile: /etc/prom-certs/root-cert.pem
            certFile: /etc/prom-certs/cert-chain.pem
            keyFile: /etc/prom-certs/key.pem
            insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate

  praefect:
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
  gitlab-grafana:
    annotations:
    # renovate this
      bigbang.dev/istioVersion: 1.17.2
shared-secrets:
  annotations:
  # renovate this
    bigbang.dev/istioVersion: 1.17.2
minio:
  podAnnotations:
  # renovate this
    bigbang.dev/istioVersion: 1.17.2

global:

  # added to help with Gitlab sub-chart configuration
  image:
    pullPolicy: IfNotPresent

  istio:
    enabled: true
    injection: enabled

  hosts:
    domain: bigbang.dev

    gitlab:
      name: gitlab.bigbang.dev

    registry:
      name: registry.bigbang.dev
