apiVersion: v1
kind: Secret
metadata:
  name: gitlab-sso-provider
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  gitlab-sso.json: |-
    {
      "name": "openid_connect",
      "label": "SSO",
      "args": {
        "name": "openid_connect",
        "scope": [
          "Gitlab"
        ],
        "response_type": "code",
        "issuer": "https://###ZARF_VAR_KEYCLOAK_DOMAIN###/auth/realms/###ZARF_VAR_KEYCLOAK_REALM###",
        "client_auth_method": "query",
        "discovery": true,
        "uid_field": "preferred_username",
        "client_options": {
          "identifier": "###ZARF_VAR_KEYCLOAK_CLIENT###",
          "secret": "###ZARF_VAR_KEYCLOAK_CLIENT_SECRET###",
          "redirect_uri": "https://gitlab.###ZARF_VAR_DOMAIN###/users/auth/openid_connect/callback",
          "end_session_endpoint": "https://###ZARF_VAR_KEYCLOAK_DOMAIN###/auth/realms/###ZARF_VAR_KEYCLOAK_REALM###/protocol/openid-connect/logout"
        }
      }
    }
