apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: gitlab-redis-external-names-exception
  namespace: kyverno
spec:
  exceptions:
  - policyName: restrict-external-names
    ruleNames:
    - external-names
  match:
    any:
    - resources:
        kinds:
        - Service
        namespaces:
        - gitlab
        names:
        - gitlab-redis
