apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: gitlab-minio-host-path-exception
  namespace: gitlab-minio
spec:
  exceptions:
  - policyName: restrict-host-path-write
    ruleNames:
    - require-readonly-hostpath
  match:
    any:
    - resources:
        kinds:
        - Pod
        namespaces:
        - gitlab-minio
        names:
        - minio-post-job-*
