name: Check Package Version Update

on:
  pull_request:
    branches:
      - 'main' # This runs the action on pull request events for the main branch

permissions:
  id-token: write
  contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install yq and semver-tool
      run: |
        sudo snap install yq
        git clone https://github.com/fsaintjacques/semver-tool.git
        chmod +x semver-tool/src/semver

    - name: Extract package version from PR
      id: pr-version
      run: echo "::set-output name=version::$(yq eval '.package.create.set.package_version' zarf-config.yaml)"

    - name: Extract package version from main
      id: main-version
      run: echo "::set-output name=version::$(git show origin/main:zarf-config.yaml | yq eval '.package.create.set.package_version' -)"

    - name: Compare versions
      run: |
        validation_result=$(semver-tool/src/semver validate "${{ steps.pr-version.outputs.version }}")
        echo $validation_result

        if [ "$validation_result" = "valid" ] && semver-tool/src/semver compare "${{ steps.pr-version.outputs.version }}" "${{ steps.main-version.outputs.version }}" -eq 1; then
          echo "Version updated successfully."
        else
          echo "Version has not been updated properly according to Semantic Versioning!"
          exit 1
        fi
